import type { QuestaoPrf } from "../../data/prf";

export const QUESTOES_PRF_CON: QuestaoPrf[] = [
  {
    id: "prf-con-001",
    materia: "con",
    topico: "Constituição: conceito, classificações e princípios fundamentais",
    enunciado: "Quanto à classificação, a Constituição Federal de 1988 é considerada",
    alternativas: [
      "outorgada, escrita, dogmática, rígida e sintética.",
      "promulgada, costumeira, histórica, flexível e analítica.",
      "promulgada, escrita, dogmática, rígida e analítica.",
      "promulgada, escrita, dogmática, semirrígida e sintética.",
      "cesarista, escrita, histórica, rígida e analítica.",
    ],
    correta: 2,
    explicacao:
      "A Constituição de 1988 foi votada por Assembleia Constituinte eleita (promulgada), está num documento único (escrita), foi elaborada de uma vez (dogmática), exige processo especial de emenda (rígida) e é longa e detalhada (analítica). Outorgadas foram as de 1824, 1937 e 1967; a cesarista é imposta e depois submetida a plebiscito; a semirrígida exige processo especial só para parte do texto.",
    origem: "banco",
  },
  {
    id: "prf-con-002",
    materia: "con",
    topico: "Constituição: conceito, classificações e princípios fundamentais",
    enunciado: "Entre os objetivos fundamentais da República Federativa do Brasil, previstos no art. 3º da Constituição, está",
    alternativas: [
      "a dignidade da pessoa humana, ao lado da soberania e da cidadania.",
      "erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais.",
      "a prevalência dos direitos humanos nas relações internacionais do País.",
      "erradicar as desigualdades sociais e regionais e reduzir a pobreza e a marginalização.",
      "o pluralismo político, que assegura a convivência de diferentes ideologias.",
    ],
    correta: 1,
    explicacao:
      "O art. 3º, III, manda erradicar a pobreza e a marginalização e reduzir as desigualdades sociais e regionais; a versão que troca os verbos está errada. Dignidade da pessoa humana, soberania, cidadania e pluralismo político são fundamentos (art. 1º), e a prevalência dos direitos humanos é princípio das relações internacionais (art. 4º).",
    origem: "banco",
  },
  {
    id: "prf-con-003",
    materia: "con",
    topico: "Constituição: conceito, classificações e princípios fundamentais",
    enunciado: "Nas relações internacionais, a República Federativa do Brasil rege-se, entre outros, pelo princípio da",
    alternativas: [
      "intervenção nos Estados que violem direitos humanos.",
      "garantia do desenvolvimento nacional.",
      "soberania popular, exercida pelo sufrágio universal.",
      "integração econômica exclusiva com os países do Mercosul.",
      "concessão de asilo político.",
    ],
    correta: 4,
    explicacao:
      "A concessão de asilo político está no art. 4º, X. O princípio é o da não intervenção (art. 4º, IV), e não o contrário; garantir o desenvolvimento nacional é objetivo fundamental (art. 3º, II); a soberania popular aparece nos arts. 1º e 14; e o parágrafo único do art. 4º fala em integração com os povos da América Latina, sem exclusividade.",
    origem: "banco",
  },
  {
    id: "prf-con-004",
    materia: "con",
    topico: "Direitos e deveres individuais e coletivos",
    enunciado: "De acordo com o art. 5º da Constituição, sem o consentimento do morador, é permitido entrar na casa",
    alternativas: [
      "em caso de flagrante delito, a qualquer hora, ou por determinação judicial, durante o dia.",
      "por determinação judicial, a qualquer hora, ou em caso de flagrante delito, só durante o dia.",
      "por ordem escrita da autoridade policial, desde que durante o dia e com duas testemunhas.",
      "apenas por determinação judicial, que pode ser cumprida durante o dia ou durante a noite.",
      "em caso de desastre ou para prestar socorro, mas só com autorização judicial prévia.",
    ],
    correta: 0,
    explicacao:
      "Pelo art. 5º, XI, a casa é asilo inviolável: sem consentimento do morador, só se entra em caso de flagrante delito, desastre ou para prestar socorro, a qualquer hora, ou por determinação judicial, durante o dia. A ordem judicial não autoriza o ingresso noturno, a autoridade policial não expede ordem de ingresso, e desastre e socorro dispensam autorização.",
    origem: "banco",
  },
  {
    id: "prf-con-005",
    materia: "con",
    topico: "Direitos e deveres individuais e coletivos",
    enunciado:
      "Um servidor descobre que um cadastro mantido por órgão público registra dados incorretos sobre ele, e o pedido administrativo de acesso e correção foi negado. O remédio constitucional próprio para conhecer e retificar essas informações é o",
    alternativas: [
      "habeas corpus, porque a recusa ameaça indiretamente sua liberdade de locomoção.",
      "mandado de injunção, porque falta norma que regulamente o acesso aos dados.",
      "mandado de segurança coletivo, que só pode ser impetrado por partido político.",
      "habeas data, que também serve para retificar dados e é uma ação gratuita.",
      "ação popular, que qualquer cidadão pode propor para anular ato lesivo.",
    ],
    correta: 3,
    explicacao:
      "O habeas data (art. 5º, LXXII) assegura o conhecimento de informações pessoais constantes de registros de entidades governamentais ou de caráter público e a retificação de dados, e é gratuito (LXXVII). Não há ameaça à locomoção (HC) nem falta de norma (MI); o mandado de segurança coletivo também pode ser impetrado por sindicato, entidade de classe ou associação; e a ação popular protege o patrimônio público, não dados pessoais.",
    origem: "banco",
  },
  {
    id: "prf-con-006",
    materia: "con",
    topico: "Direitos e deveres individuais e coletivos",
    enunciado: "Sobre os direitos de reunião e de associação, a afirmação que está de acordo com a Constituição é:",
    alternativas: [
      "A reunião pacífica em local aberto ao público depende de autorização da autoridade competente.",
      "As associações podem ter suas atividades suspensas por decisão administrativa fundamentada.",
      "A dissolução compulsória de associação exige decisão judicial transitada em julgado.",
      "A criação de associações depende de autorização do poder público, que fiscaliza seu funcionamento.",
      "Admite-se associação de caráter paramilitar, desde que seus fins sejam lícitos e declarados.",
    ],
    correta: 2,
    explicacao:
      "O art. 5º, XIX, exige decisão judicial para suspender as atividades e decisão judicial transitada em julgado para a dissolução compulsória. A reunião pacífica dispensa autorização, bastando aviso prévio (XVI); a criação de associações independe de autorização, vedada a interferência estatal (XVIII); e a associação paramilitar é proibida (XVII).",
    origem: "banco",
  },
  {
    id: "prf-con-007",
    materia: "con",
    topico: "Direitos sociais",
    enunciado: "De acordo com o art. 6º da Constituição, são direitos sociais, entre outros,",
    alternativas: [
      "a alimentação, o transporte, a moradia e a segurança.",
      "a propriedade, a liberdade de crença, a moradia e a segurança.",
      "a alimentação, o transporte, a nacionalidade e o voto.",
      "a herança, a moradia, o lazer e a livre iniciativa.",
      "a inviolabilidade do domicílio, o trabalho e a saúde.",
    ],
    correta: 0,
    explicacao:
      "O art. 6º lista educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência social, proteção à maternidade e à infância e assistência aos desamparados. Propriedade, liberdade de crença, herança e inviolabilidade do domicílio são direitos individuais do art. 5º; a livre iniciativa é fundamento da República; nacionalidade e voto têm capítulos próprios.",
    origem: "banco",
  },
  {
    id: "prf-con-008",
    materia: "con",
    topico: "Direitos sociais",
    enunciado: "Entre os direitos dos trabalhadores urbanos e rurais previstos no art. 7º da Constituição, está",
    alternativas: [
      "a jornada normal de até seis horas diárias e trinta e seis semanais, para todas as categorias.",
      "o salário mínimo fixado por Estado, que pode servir de indexador de outros valores.",
      "o repouso semanal remunerado, obrigatoriamente aos domingos, sem nenhuma exceção.",
      "a duração normal do trabalho de até oito horas diárias e quarenta e quatro semanais.",
      "o trabalho noturno permitido a partir dos dezesseis anos, inclusive em atividade insalubre.",
    ],
    correta: 3,
    explicacao:
      "O art. 7º, XIII, fixa a duração normal em até oito horas diárias e quarenta e quatro semanais, facultadas compensação e redução por acordo ou convenção. A jornada de seis horas vale para turnos ininterruptos de revezamento (XIV); o salário mínimo é nacionalmente unificado e não pode ser vinculado (IV); o repouso é preferencialmente aos domingos (XV); e o trabalho noturno, perigoso ou insalubre é proibido aos menores de dezoito anos (XXXIII).",
    origem: "banco",
  },
  {
    id: "prf-con-009",
    materia: "con",
    topico: "Direitos sociais",
    enunciado: "Sobre a associação profissional ou sindical, a Constituição estabelece que",
    alternativas: [
      "é permitida a criação de mais de um sindicato da mesma categoria no mesmo Município.",
      "ninguém será obrigado a filiar-se ou a manter-se filiado a sindicato.",
      "a fundação de sindicato depende de autorização prévia do Ministério do Trabalho.",
      "o empregado sindicalizado pode ser dispensado livremente durante o mandato sindical.",
      "o servidor público civil não tem direito à livre associação sindical.",
    ],
    correta: 1,
    explicacao:
      "O art. 8º, V, garante a liberdade de não se filiar e de se desfiliar. A unicidade sindical veda mais de uma organização da mesma categoria na mesma base territorial, não inferior a um Município (II); a lei não pode exigir autorização do Estado, ressalvado o registro (I); o dirigente sindical tem estabilidade desde a candidatura até um ano após o mandato, salvo falta grave (VIII); e o servidor civil tem direito à associação sindical (art. 37, VI).",
    origem: "banco",
  },
  {
    id: "prf-con-010",
    materia: "con",
    topico: "Nacionalidade",
    enunciado: "É brasileiro nato, segundo a Constituição,",
    alternativas: [
      "o nascido no Brasil, filho de pais estrangeiros que estejam a serviço do país de origem.",
      "o estrangeiro residente no Brasil há mais de quinze anos ininterruptos, sem condenação penal.",
      "o português com residência permanente no País, se houver reciprocidade em favor de brasileiros.",
      "o originário de país de língua portuguesa que resida no Brasil por um ano ininterrupto.",
      "o nascido no estrangeiro, de mãe brasileira, registrado em repartição brasileira competente.",
    ],
    correta: 4,
    explicacao:
      "O art. 12, I, c, considera nato o nascido no estrangeiro de pai ou mãe brasileiros registrado em repartição brasileira competente. O filho de estrangeiros a serviço de seu país não é nato (I, a); a residência por quinze anos e a residência por um ano (países de língua portuguesa) são hipóteses de naturalização (II); e ao português com residência permanente se atribuem direitos de brasileiro, sem torná-lo nato (§ 1º).",
    origem: "banco",
  },
  {
    id: "prf-con-011",
    materia: "con",
    topico: "Nacionalidade",
    enunciado: "É cargo privativo de brasileiro nato o de",
    alternativas: [
      "Ministro de Estado da Justiça e Segurança Pública.",
      "Senador da República.",
      "Ministro de Estado da Defesa.",
      "Ministro do Superior Tribunal de Justiça.",
      "Procurador-Geral da República.",
    ],
    correta: 2,
    explicacao:
      "O art. 12, § 3º, reserva a brasileiros natos os cargos de Presidente e Vice-Presidente da República, Presidente da Câmara, Presidente do Senado, Ministro do STF, carreira diplomática, oficial das Forças Armadas e Ministro de Estado da Defesa. Os demais cargos citados podem ser ocupados por naturalizados.",
    origem: "banco",
  },
  {
    id: "prf-con-012",
    materia: "con",
    topico: "Nacionalidade",
    enunciado: "Segundo a redação atual do art. 12, § 4º, da Constituição, será declarada a perda da nacionalidade do brasileiro que",
    alternativas: [
      "adquirir voluntariamente outra nacionalidade, ainda que isso não gere situação de apatridia.",
      "pedir expressamente a perda à autoridade brasileira competente, salvo risco de apatridia.",
      "tiver a naturalização cancelada por ato administrativo do Ministro da Justiça, por fraude.",
      "for condenado por crime comum, com sentença transitada em julgado, ainda que seja nato.",
      "residir no exterior por mais de quinze anos, salvo se isso gerar situação de apatridia.",
    ],
    correta: 1,
    explicacao:
      "Desde a EC 131/2023, o § 4º prevê duas hipóteses: cancelamento da naturalização por sentença judicial, por fraude no processo de naturalização ou atentado contra a ordem constitucional e o Estado Democrático, e pedido expresso de perda, ressalvadas as situações de apatridia. A aquisição de outra nacionalidade deixou de ser causa de perda, o cancelamento depende de sentença e não de ato administrativo, e condenação criminal ou residência no exterior não fazem perder a nacionalidade.",
    origem: "banco",
  },
  {
    id: "prf-con-013",
    materia: "con",
    topico: "Direitos políticos e partidos políticos",
    enunciado: "Segundo a Constituição, o alistamento eleitoral e o voto são facultativos para",
    alternativas: [
      "os analfabetos, os maiores de sessenta anos e os maiores de dezesseis e menores de dezoito anos.",
      "os conscritos, durante o serviço militar obrigatório, e os maiores de setenta anos.",
      "os estrangeiros residentes há mais de quinze anos e os maiores de setenta anos.",
      "os analfabetos, os maiores de setenta anos e os maiores de dezesseis e menores de dezoito anos.",
      "os servidores públicos em serviço no dia da eleição e os maiores de sessenta e cinco anos.",
    ],
    correta: 3,
    explicacao:
      "O art. 14, § 1º, II, torna facultativos o alistamento e o voto para os analfabetos, os maiores de setenta anos e os maiores de dezesseis e menores de dezoito. Os conscritos, durante o serviço militar obrigatório, e os estrangeiros não podem alistar-se (§ 2º), e a idade é setenta anos, não sessenta nem sessenta e cinco.",
    origem: "banco",
  },
  {
    id: "prf-con-014",
    materia: "con",
    topico: "Direitos políticos e partidos políticos",
    enunciado: "A idade mínima exigida pela Constituição como condição de elegibilidade é de",
    alternativas: [
      "trinta e cinco anos para Governador e vinte e um anos para Prefeito.",
      "trinta anos para Senador e dezoito anos para Prefeito.",
      "vinte e um anos para Vereador e trinta anos para Deputado Federal.",
      "trinta e cinco anos para Deputado Federal e trinta anos para Senador.",
      "trinta anos para Governador e vinte e um anos para Prefeito.",
    ],
    correta: 4,
    explicacao:
      "O art. 14, § 3º, VI, exige 35 anos para Presidente, Vice-Presidente e Senador; 30 para Governador e Vice-Governador; 21 para Deputado Federal, Estadual ou Distrital, Prefeito, Vice-Prefeito e juiz de paz; e 18 para Vereador.",
    origem: "banco",
  },
  {
    id: "prf-con-015",
    materia: "con",
    topico: "Direitos políticos e partidos políticos",
    enunciado: "Sobre os partidos políticos, a Constituição estabelece que",
    alternativas: [
      "devem ter caráter nacional e prestar contas à Justiça Eleitoral.",
      "podem receber recursos de governos estrangeiros, desde que declarados à Justiça Eleitoral.",
      "adquirem personalidade jurídica com o registro de seus estatutos no Tribunal Superior Eleitoral.",
      "podem celebrar coligações tanto nas eleições majoritárias quanto nas proporcionais.",
      "podem manter organização paramilitar, desde que vinculada à defesa do regime democrático.",
    ],
    correta: 0,
    explicacao:
      "O art. 17 exige caráter nacional (I) e prestação de contas à Justiça Eleitoral (III). É proibido receber recursos de entidade ou governo estrangeiros (II); a personalidade jurídica é adquirida na forma da lei civil, e só depois os estatutos são registrados no TSE (§ 2º); as coligações são vedadas nas eleições proporcionais (§ 1º); e o uso de organização paramilitar é proibido (§ 4º).",
    origem: "banco",
  },
  {
    id: "prf-con-016",
    materia: "con",
    topico: "Organização político-administrativa",
    enunciado: "Segundo a Constituição, legislar sobre trânsito e transporte é competência",
    alternativas: [
      "concorrente da União, dos Estados e do DF, cabendo à União editar apenas normas gerais.",
      "privativa da União, admitida delegação aos Estados por lei complementar.",
      "comum da União, dos Estados, do DF e dos Municípios, sem hierarquia entre os entes.",
      "exclusiva dos Estados, por ser matéria de interesse regional, vedada qualquer delegação.",
      "privativa dos Municípios, por se tratar de assunto de interesse local da população.",
    ],
    correta: 1,
    explicacao:
      "Trânsito e transporte estão no art. 22, XI, entre as competências legislativas privativas da União, e o parágrafo único permite que lei complementar autorize os Estados a legislar sobre questões específicas. A competência comum do art. 23, XII, é administrativa e trata da política de educação para a segurança do trânsito.",
    origem: "banco",
  },
  {
    id: "prf-con-017",
    materia: "con",
    topico: "Organização político-administrativa",
    enunciado: "Os Territórios Federais, segundo a Constituição,",
    alternativas: [
      "são entes federativos autônomos, ao lado dos Estados, do DF e dos Municípios.",
      "elegem três senadores cada um, com mandato de oito anos.",
      "integram o Estado de origem e são criados por lei estadual.",
      "integram a União, e sua criação é regulada em lei complementar.",
      "não elegem deputados federais, pois não têm representação no Congresso.",
    ],
    correta: 3,
    explicacao:
      "Pelo art. 18, § 2º, os Territórios integram a União, e lei complementar regula sua criação, transformação em Estado ou reintegração ao Estado de origem. Não são entes autônomos, não elegem senadores (o art. 46 fala em Estados e DF) e, se criados, elegem quatro deputados federais cada um (art. 45, § 2º).",
    origem: "banco",
  },
  {
    id: "prf-con-018",
    materia: "con",
    topico: "Organização político-administrativa",
    enunciado: "A criação de um novo Município depende, segundo a Constituição, de",
    alternativas: [
      "lei federal, no período fixado por lei complementar estadual, e plebiscito em todos os Municípios do Estado.",
      "lei complementar federal e de referendo apenas na população do Município a ser criado.",
      "decreto do Governador, depois de aprovado o estudo de viabilidade pela Assembleia Legislativa.",
      "lei municipal do Município de origem, dispensada a consulta à população envolvida.",
      "lei estadual, no período fixado por lei complementar federal, e plebiscito nos Municípios envolvidos.",
    ],
    correta: 4,
    explicacao:
      "O art. 18, § 4º, exige lei estadual, dentro do período determinado por lei complementar federal, consulta prévia por plebiscito às populações dos Municípios envolvidos e divulgação dos Estudos de Viabilidade Municipal. Não se trata de lei federal, decreto, lei municipal ou referendo.",
    origem: "banco",
  },
  {
    id: "prf-con-019",
    materia: "con",
    topico: "Administração pública e servidores públicos",
    enunciado: "Segundo o art. 37 da Constituição, o prazo de validade do concurso público é de",
    alternativas: [
      "até dois anos, prorrogável uma vez, por igual período.",
      "até dois anos, prorrogável sucessivas vezes, a critério da administração.",
      "dois anos, improrrogável, contado da homologação do resultado.",
      "até quatro anos, prorrogável uma vez, por metade do período.",
      "até um ano, prorrogável uma vez, por período de até dois anos.",
    ],
    correta: 0,
    explicacao:
      "O art. 37, III, fixa a validade em até dois anos, prorrogável uma vez, por igual período. Durante o prazo improrrogável previsto no edital, o aprovado tem prioridade sobre novos concursados para assumir o cargo (IV).",
    origem: "banco",
  },
  {
    id: "prf-con-020",
    materia: "con",
    topico: "Administração pública e servidores públicos",
    enunciado:
      "Considerando a redação atual do art. 37, XVI, da Constituição, havendo compatibilidade de horários e respeitado o teto remuneratório, é permitida a acumulação remunerada de",
    alternativas: [
      "dois cargos de agente administrativo, desde que em órgãos de esferas diferentes.",
      "dois cargos técnicos ou científicos, ainda que nenhum deles seja de professor.",
      "um cargo de professor com outro de qualquer natureza.",
      "dois cargos privativos de profissionais de saúde, ainda que a profissão não seja regulamentada.",
      "dois empregos em empresas públicas, porque a proibição alcança apenas os cargos.",
    ],
    correta: 2,
    explicacao:
      "A EC 138/2025 deu nova redação à alínea b do art. 37, XVI: além de dois cargos de professor e de dois cargos ou empregos privativos de profissionais de saúde com profissões regulamentadas, passou a ser permitido acumular um cargo de professor com outro de qualquer natureza (antes, exigia-se que fosse técnico ou científico). Dois cargos que não sejam de professor nem de saúde não se acumulam, e a proibição alcança empregos e funções na administração indireta (XVII).",
    origem: "banco",
  },
  {
    id: "prf-con-021",
    materia: "con",
    topico: "Administração pública e servidores públicos",
    enunciado: "Sobre a estabilidade do servidor público, prevista no art. 41 da Constituição, é correto afirmar que",
    alternativas: [
      "é adquirida após dois anos de efetivo exercício, dispensada a avaliação de desempenho.",
      "alcança também os ocupantes de cargo em comissão, após três anos de exercício.",
      "depois de adquirida, o servidor só perde o cargo por sentença judicial transitada em julgado.",
      "exige três anos de efetivo exercício e aprovação em avaliação especial de desempenho.",
      "extinto o cargo, o servidor estável é exonerado e recebe indenização proporcional.",
    ],
    correta: 3,
    explicacao:
      "O art. 41 exige três anos de efetivo exercício em cargo efetivo, por concurso, e aprovação em avaliação especial de desempenho (§ 4º). O estável também pode perder o cargo por processo administrativo com ampla defesa e por avaliação periódica de desempenho (§ 1º); extinto o cargo, fica em disponibilidade, com remuneração proporcional ao tempo de serviço (§ 3º).",
    origem: "banco",
  },
  {
    id: "prf-con-022",
    materia: "con",
    topico: "Poder Legislativo",
    enunciado: "Quanto à composição do Congresso Nacional, a Constituição estabelece que",
    alternativas: [
      "cada Estado e o DF elegem dois senadores, com mandato de quatro anos, cada um com três suplentes.",
      "os senadores são eleitos pelo sistema proporcional, e os deputados, pelo majoritário.",
      "nenhum Estado pode ter menos de quatro nem mais de setenta deputados federais.",
      "a representação dos Estados no Senado é renovada integralmente a cada quatro anos.",
      "cada Estado e o DF elegem três senadores, com mandato de oito anos, cada um com dois suplentes.",
    ],
    correta: 4,
    explicacao:
      "Pelo art. 46, cada Estado e o DF elegem três senadores, pelo princípio majoritário, com mandato de oito anos e dois suplentes cada; a representação é renovada de quatro em quatro anos, alternadamente, por um e dois terços. Os deputados são eleitos pelo sistema proporcional, e nenhuma unidade tem menos de oito nem mais de setenta (art. 45, § 1º).",
    origem: "banco",
  },
  {
    id: "prf-con-023",
    materia: "con",
    topico: "Poder Legislativo",
    enunciado: "Desde a expedição do diploma, deputados e senadores",
    alternativas: [
      "só podem ser presos em flagrante de crime inafiançável, e a Casa resolve sobre a prisão.",
      "não podem ser presos em nenhuma hipótese, nem mesmo em flagrante de crime inafiançável.",
      "só podem ser processados criminalmente com licença prévia da Casa respectiva.",
      "são julgados pelo Superior Tribunal de Justiça nas infrações penais comuns.",
      "podem ser presos em flagrante de qualquer crime, comunicando-se o fato ao STF em 24 horas.",
    ],
    correta: 0,
    explicacao:
      "Pelo art. 53, § 2º, desde a diplomação os parlamentares só podem ser presos em flagrante de crime inafiançável, e os autos vão em 24 horas à Casa, que resolve sobre a prisão pelo voto da maioria de seus membros. Não há licença prévia para o processo, apenas a possibilidade de sustação (§ 3º), e o julgamento é no STF (§ 1º).",
    origem: "banco",
  },
  {
    id: "prf-con-024",
    materia: "con",
    topico: "Poder Legislativo",
    enunciado:
      "Uma CPI da Câmara dos Deputados investiga fraudes em contratos de manutenção de rodovias federais. Segundo a Constituição e a jurisprudência do STF, essa comissão",
    alternativas: [
      "pode decretar a interceptação telefônica dos investigados, por ter poderes de juiz.",
      "pode quebrar o sigilo bancário dos investigados, por decisão fundamentada.",
      "pode ser criada por requerimento de um quinto dos deputados, por prazo indeterminado.",
      "pode expedir mandado de busca e apreensão em residência, durante o dia.",
      "pode aplicar diretamente as penas aos responsáveis, ao final dos trabalhos.",
    ],
    correta: 1,
    explicacao:
      "As CPIs têm poderes de investigação próprios das autoridades judiciais (art. 58, § 3º) e podem quebrar sigilos bancário, fiscal e de dados por decisão fundamentada. Interceptação telefônica, busca domiciliar e prisão (salvo flagrante) dependem de ordem judicial. A CPI é criada por um terço dos membros, para fato determinado e por prazo certo, e envia suas conclusões ao Ministério Público, sem aplicar penas.",
    origem: "banco",
  },
  {
    id: "prf-con-025",
    materia: "con",
    topico: "Poder Executivo",
    enunciado:
      "Em caso de impedimento simultâneo do Presidente e do Vice-Presidente da República, serão chamados ao exercício da Presidência, sucessivamente,",
    alternativas: [
      "o Presidente do Senado, o Presidente da Câmara e o Presidente do STF.",
      "o Presidente do STF, o Presidente da Câmara e o Presidente do Senado.",
      "o Presidente da Câmara, o Presidente do Senado e o Presidente do STF.",
      "o Presidente do Congresso, o Presidente do STF e o Procurador-Geral da República.",
      "o Ministro da Casa Civil, o Presidente da Câmara e o Presidente do Senado.",
    ],
    correta: 2,
    explicacao:
      "Pelo art. 80, a linha sucessória depois do Vice é: Presidente da Câmara dos Deputados, Presidente do Senado Federal e Presidente do STF. Eles apenas exercem a Presidência temporariamente; vagos os dois cargos, faz-se nova eleição (art. 81).",
    origem: "banco",
  },
  {
    id: "prf-con-026",
    materia: "con",
    topico: "Poder Executivo",
    enunciado:
      "Vagando os cargos de Presidente e de Vice-Presidente da República no terceiro ano do mandato, a Constituição determina que",
    alternativas: [
      "o Presidente da Câmara assuma a Presidência até o fim do mandato.",
      "haja eleição direta noventa dias depois de aberta a última vaga.",
      "o Congresso Nacional eleja ambos noventa dias depois da última vaga, para novo mandato de quatro anos.",
      "o Congresso Nacional eleja ambos trinta dias depois da última vaga, para completar o período.",
      "haja eleição direta trinta dias depois da última vaga, para novo mandato de quatro anos.",
    ],
    correta: 3,
    explicacao:
      "O art. 81 manda fazer eleição noventa dias depois da última vaga; mas, se a vacância ocorrer nos últimos dois anos do período presidencial, a eleição para ambos os cargos é feita trinta dias depois, pelo Congresso Nacional. Em qualquer caso, os eleitos apenas completam o período dos antecessores (§ 2º).",
    origem: "banco",
  },
  {
    id: "prf-con-027",
    materia: "con",
    topico: "Poder Executivo",
    enunciado:
      "Entre as atribuições do Presidente da República, a Constituição permite delegar aos Ministros de Estado, ao Procurador-Geral da República ou ao Advogado-Geral da União a de",
    alternativas: [
      "sancionar, promulgar e fazer publicar as leis.",
      "vetar projetos de lei, total ou parcialmente.",
      "nomear os Ministros do Supremo Tribunal Federal.",
      "decretar o estado de defesa e o estado de sítio.",
      "conceder indulto e comutar penas.",
    ],
    correta: 4,
    explicacao:
      "O parágrafo único do art. 84 só permite delegar as atribuições dos incisos VI (decretos sobre organização e funcionamento da administração federal e extinção de cargos vagos), XII (indulto e comutação de penas) e XXV, primeira parte (prover cargos públicos federais). Sanção, veto, nomeação de Ministros do STF e decretação de estado de defesa ou de sítio são indelegáveis.",
    origem: "banco",
  },
  {
    id: "prf-con-028",
    materia: "con",
    topico: "Poder Judiciário e CNJ",
    enunciado: "Sobre o Conselho Nacional de Justiça, é correto afirmar, segundo a Constituição, que",
    alternativas: [
      "é presidido pelo Presidente do STF e controla a atuação administrativa e financeira do Judiciário.",
      "é presidido pelo Ministro do STJ e pode rever as sentenças proferidas pelos juízes de primeiro grau.",
      "tem onze membros, com mandato de quatro anos, vedada a recondução.",
      "não integra o Poder Judiciário, por ser órgão de controle externo vinculado ao Senado.",
      "é presidido pelo Presidente do STF e julga recursos contra decisões judiciais dos tribunais.",
    ],
    correta: 0,
    explicacao:
      "O CNJ integra o Poder Judiciário (art. 92, I-A), tem quinze membros com mandato de dois anos, admitida uma recondução, e é presidido pelo Presidente do STF (art. 103-B, § 1º). Compete-lhe o controle da atuação administrativa e financeira do Judiciário e do cumprimento dos deveres funcionais dos juízes; não tem função jurisdicional, por isso não revê sentenças nem julga recursos. O Ministro do STJ é o Corregedor.",
    origem: "banco",
  },
  {
    id: "prf-con-029",
    materia: "con",
    topico: "Poder Judiciário e CNJ",
    enunciado: "Quanto às garantias e vedações da magistratura, a Constituição estabelece que o juiz de primeiro grau",
    alternativas: [
      "torna-se vitalício após dois anos; antes, a perda do cargo depende de deliberação do tribunal.",
      "torna-se vitalício no ato da posse e só perde o cargo por sentença judicial transitada em julgado.",
      "torna-se vitalício após três anos de exercício, como ocorre com os servidores estáveis.",
      "pode exercer outro cargo ou função pública, além de uma de magistério, se houver compatibilidade.",
      "pode advogar no juízo do qual se afastou logo após a aposentadoria, sem prazo de espera.",
    ],
    correta: 0,
    explicacao:
      "Pelo art. 95, I, a vitaliciedade no primeiro grau só é adquirida após dois anos de exercício; nesse período, a perda do cargo depende de deliberação do tribunal e, depois, de sentença judicial transitada em julgado. O juiz não pode exercer outro cargo ou função, salvo uma de magistério, e só pode advogar no juízo ou tribunal de que se afastou depois de três anos (parágrafo único, I e V).",
    origem: "banco",
  },
  {
    id: "prf-con-030",
    materia: "con",
    topico: "Poder Judiciário e CNJ",
    enunciado: "O Supremo Tribunal Federal, segundo a Constituição,",
    alternativas: [
      "tem quinze Ministros, escolhidos entre juízes de carreira com mais de trinta e cinco anos de idade.",
      "tem onze Ministros, escolhidos entre cidadãos com mais de trinta e cinco e menos de setenta anos.",
      "tem onze Ministros, nomeados pelo Presidente da República sem necessidade de aprovação do Senado.",
      "tem onze Ministros, escolhidos entre brasileiros natos ou naturalizados com mais de trinta anos.",
      "tem onze Ministros, eleitos pelo Congresso Nacional para mandato fixo de oito anos.",
    ],
    correta: 1,
    explicacao:
      "O art. 101 fixa onze Ministros, escolhidos entre cidadãos com mais de trinta e cinco e menos de setenta anos, de notável saber jurídico e reputação ilibada, nomeados pelo Presidente da República depois de aprovada a escolha pela maioria absoluta do Senado. O cargo é privativo de brasileiro nato (art. 12, § 3º, IV), não exige carreira na magistratura e não tem mandato fixo.",
    origem: "banco",
  },
  {
    id: "prf-con-031",
    materia: "con",
    topico: "Funções essenciais à Justiça",
    enunciado: "Sobre a chefia do Ministério Público, a Constituição estabelece que",
    alternativas: [
      "o Procurador-Geral da República é escolhido livremente entre advogados de notável saber jurídico.",
      "o Procurador-Geral da República tem mandato de dois anos, permitida a recondução.",
      "o Procurador-Geral de Justiça tem mandato de quatro anos, permitida a recondução ilimitada.",
      "a destituição do Procurador-Geral da República independe de autorização do Senado Federal.",
      "o Procurador-Geral de Justiça é eleito diretamente pelos membros da carreira, sem lista tríplice.",
    ],
    correta: 1,
    explicacao:
      "Pelo art. 128, § 1º, o PGR é nomeado pelo Presidente entre integrantes da carreira maiores de trinta e cinco anos, após aprovação pela maioria absoluta do Senado, para mandato de dois anos, permitida a recondução; a destituição depende de autorização da maioria absoluta do Senado (§ 2º). O Procurador-Geral de Justiça é nomeado pelo chefe do Executivo a partir de lista tríplice da carreira, para mandato de dois anos, permitida uma recondução (§ 3º).",
    origem: "banco",
  },
  {
    id: "prf-con-032",
    materia: "con",
    topico: "Funções essenciais à Justiça",
    enunciado: "Entre as funções institucionais do Ministério Público previstas no art. 129 da Constituição, está a de",
    alternativas: [
      "representar judicialmente a União e prestar consultoria jurídica aos seus órgãos.",
      "promover, em caráter exclusivo, a ação civil pública e o inquérito civil.",
      "exercer o controle externo da atividade policial, na forma de lei complementar.",
      "presidir o inquérito policial nas infrações penais de competência federal.",
      "julgar administrativamente os crimes cometidos por policiais em serviço.",
    ],
    correta: 2,
    explicacao:
      "O art. 129, VII, atribui ao MP o controle externo da atividade policial, o que inclui a PRF. É vedado ao MP representar judicialmente ou prestar consultoria a entidades públicas (IX), tarefa da advocacia pública; a legitimação para a ação civil pública não é exclusiva (§ 1º); e o MP requisita a instauração de inquérito policial (VIII), mas não o preside.",
    origem: "banco",
  },
  {
    id: "prf-con-033",
    materia: "con",
    topico: "Funções essenciais à Justiça",
    enunciado: "Sobre a Advocacia-Geral da União e a Defensoria Pública, a Constituição estabelece que",
    alternativas: [
      "o Advogado-Geral da União é nomeado pelo Presidente, após aprovação de seu nome pelo Senado Federal.",
      "o ingresso na carreira da AGU se dá por livre nomeação, dispensado o concurso público.",
      "o Advogado-Geral da União é de livre nomeação do Presidente, entre maiores de trinta e cinco anos.",
      "a Defensoria Pública integra o Ministério Público e atua apenas na esfera judicial.",
      "a cobrança da dívida ativa tributária da União cabe ao Ministério Público Federal.",
    ],
    correta: 2,
    explicacao:
      "Pelo art. 131, § 1º, o Advogado-Geral da União é de livre nomeação pelo Presidente da República, entre cidadãos maiores de trinta e cinco anos, de notável saber jurídico e reputação ilibada, sem aprovação do Senado. O ingresso na carreira exige concurso de provas e títulos (§ 2º); a Defensoria é instituição própria, que atua judicial e extrajudicialmente (art. 134); e a dívida ativa tributária da União é executada pela Procuradoria-Geral da Fazenda Nacional (§ 3º).",
    origem: "banco",
  },
];
